### ISSUE TITLE
Standardizing CSS Preprocessing for resources

### ISSUE THREAD

**Issue by zet4** [DTinker/discord-resources#26]
It has come to be that some themes have started to use css preprocessors, notably @TheBITLINK's adapta rewrite is now using [Stylus](http://stylus-lang.com/) and @SpoopySaitama's new theme is using [Less](http://lesscss.org/).

My proposal is we decide on a single preprocessor for resources hence making it easier for new projects to be made and code kept in sync (instead of running ported out-of-date code)

**Comment by LewisTehMinerz** [comment]
I know, this issue was opened in 2016, however...

The only issue with having one set pre-processor is that people may prefer using (for example) Less instead of the set pre-processor which could be Sass.

**Comment by TriggerRimfire** [comment]
It's safe to say that Sass should be the single preprocessor, a vast majority uses Sass ([source](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2015-results)), second closest being LESS which can easily be converted into Sass as the syntaxes are very similar.

**Comment by LewisTehMinerz** [comment]
Yeah, just read on that. Sass should be it.

**Comment by TriggerRimfire** [comment]
Has been almost a year :thinking:
